### ISSUE TITLE
useStore 在组件被 unmount 之后还会触发 setState

### ISSUE THREAD

**Issue by yibn2008** [windyGex/royjs#13]
目前使用 useStore 时，如果在 useEffect 里做了 dispatch，当组件被 unmount 之后仍然会在内部 setState，导致 react warning

![image](https://user-images.githubusercontent.com/4136679/103051739-7d25a580-45d2-11eb-8e8b-9c1260b1eca0.png)

我看了 useStore 的内部实现，对事件进行 unsubscribe 的，但实际依然会有这个问题，这块实现得看下：

![image](https://user-images.githubusercontent.com/4136679/103052123-52881c80-45d3-11eb-81ee-d13b71279482.png)

**Comment by windyGex** [comment]
fixed@2.0.5
