### ISSUE TITLE
请问这个如何集成redux-devtool

### ISSUE THREAD

**Issue by liushuhui** [windyGex/royjs#14]
import devtools from '@royjs/core/devtools';
const store = new Store({
    state: {}
}, {
    plugins: [devtools]
})
按照这个方法不能生效

**Comment by windyGex** [comment]
![image](https://user-images.githubusercontent.com/197348/118248138-8b6b5400-b4d6-11eb-97f2-2db0c48191e5.png)

我这边是可以的哈

**Comment by liushuhui** [comment]
打开是空白的，是我下载的插件有问题吗，在原生react-redux里是没问题的 ，只不过在react-redux的createStore加了插件的参数window. Xxxx, 不知道royjs的这个需不需要也这样

**Comment by windyGex** [comment]
如果是和redux的包混用的话，优先级没有redux的高，可以单独跑个demo试试看

**Comment by liushuhui** [comment]
现在好了，谢谢
