### ISSUE TITLE
inject API中访问state的方式修改

### ISSUE THREAD

**Issue by windyGex** [windyGex/royjs#4]
## 背景

inject API一直是这样的使用方式, Royjs通过篡改App的原型链达到了使用`this.store`访问store中数据的目的。

```jsx
@inject(store)
class App extends React.Component {
    render() {
      const state = this.store.state
   }
}
```

但是存在下面的问题点

1. 对于App而言，如果我想通过inject生成多个组件，则只会最后一个store的改变会影响组件

    ```jsx
    class App extends React.Component {
        render() {
            const state = this.store.state;
        }
    }

    const StoreApp = inject(store)(App)
    const ListStoreApp = inject(listStore)(App)
    ```

    上面的代码只有listStore数据的改变才会影响到视图的刷新，所以期望将inject的方式修改成下面

2. 无论是connect还是inject都可以通过`this.props.dispatch`的方式调用action, 进行语法分析更容易。

## 实施方案

通过`this.props.state`和`this.props.dispatch`来代替`this.store.state`和`this.store.dispatch`

```jsx
class App extends React.Component {
    render() {
        const state = this.props.state;
    }
}

const StoreApp = inject(store)(App)
const ListStoreApp = inject(listStore)(App)
```

**Comment by yibn2008** [comment]
对 feature 没有问题, 建议:

1. 保持 0.x 对新 API 的兼容
2. 添加工具, 支持旧 API 升级成新的 API
3. 添加 lint 规则包, 对旧的用法进行检测

**Comment by windyGex** [comment]
bf951e4
